Feature/connector
DemocracyDevelopers/colorado-rla pull request #51
Opened 2023-10-19 14:55 UTC by amitmahindrakar

2023-10-19 14:56 UTC, amitmahindrakar commented on server/eclipse-project/pom.xml
> -		<dependency>
This is not required.

2023-10-19 14:56 UTC, amitmahindrakar commented on server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/GenerateAssertions.java
> +    //TODO start: remove
This is test code until we get a list of contestNames  from request.

2023-10-19 14:57 UTC, amitmahindrakar commented on server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/GenerateAssertions.java
> +    raireResponse.stream().forEach(auditResponse -> {
This can do with a bit of cleanup. I especially don't like line number 171.

2023-10-23 00:44 UTC, vteague requested changes

2023-10-23 00:44 UTC, vteague commented on server/eclipse-project/src/main/java/us/freeandfair/corla/endpoint/GenerateAssertions.java
> +    raireResponse.stream().forEach(auditResponse -> {
And on line 182 we'll need the new NEN assertion to have the relevant data, e.g. winner, loser, continuing candidates, analogous to new NEBAssertion in ln 177.

The universeSize is the whole collection of ballots being audited in this 'universe', which is either the whole county for county-wide contests, or the whole state for statewide contests. I'll explain how to find it.

2023-10-28 07:39 UTC, vteague approved these changes

2023-10-28 09:03 UTC, merged